### ISSUE TITLE
"my" variable $sid masks earlier declaration in same scope at /usr/local/bin/session line 194

### ISSUE THREAD

**Issue by curiousercreative** [arnon-weinberg/session#1]
After installing as described in article:
1. `wget https://github.com/arnon-weinberg/session/raw/master/session`
1. `chmod +x session`
1. `sudo mv session /usr/local/bin`

Output below is observed 
```bash
$ session save
"my" variable $sid masks earlier declaration in same scope at /usr/local/bin/session line 194.
Session saved.

$ session restore
"my" variable $sid masks earlier declaration in same scope at /usr/local/bin/session line 194.
Restoring session.
```
And windows present during `session save` do not visibly restore after closing windows and running any of `session restore matching|missing|existing`

Could be related to package `xorg-x11-utils` not being found in `apt`?

pop_os (ubuntu) 20.04
5.8.0-7630-generic
gnome v3.36.3
X11
windows not restored: mattermost and slack (flatpaks)

**Comment by happybeing** [comment]
I get the error for any session` command (including `session --help`), but the script still saves and restores pretty much everything.

```"my" variable $sid masks earlier declaration in same scope at /home/user/bin/session line 194.```

Ubuntu 20.04.1 lTS / Gnome 3.36.8 / X11

**Comment by curiousercreative** [comment]
Your comment has prompted me to retry this. Using `session save` and then `session restore missing` with one window at a time, I'm pleasantly surprised that many of my windows are being restored properly despite the warning message. The following application windows do not restore and I can perhaps debug further:
- Slack flatpak
- Tilix

The following applications restored nicely:
- Firefox
- Chromium
- Mattermost (flatpak)
- Thunderbird (window geometry restore is delayed, but accurate)
- Atom
- Nautilus

**Comment by happybeing** [comment]
Glad it is part working for you. Ironically I've had the opposite experience. It has worked reasonably for a while even with that message, but yesterday it failed twice so I gave up.

Earlier I noticed that after a successful restore there has been a process left running that was taking a lot of CPU and draining my laptop battery fast. So I was ready for that. But yesterday it didn't seem to complete the command line and if I kill that, all the windows it had opened disappeared. I tried it twice with different settings and had the same result so I may do without now.

**Comment by arnon-weinberg** [comment]
Sorry I didn't see these posts earlier - not sure why GitHub does not notify me.  The message from line 194 is just a compiler warning and should not affect execution.  My version of Perl is very old, so I cannot reproduce it right now.

If you would like help getting the script working again, then please copy+paste the output with full debug:
`>session restore missing --debug=3`
